name: Pre Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: prerelease

      - run: echo ${{ steps.bump-semver.outputs.new_version }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: ${{ steps.bump-semver.outputs.new_version }}
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
